version: '3.8'

volumes:
  mysql_data:

services:
  mysql:
    image: library/mysql:8.0.21
    volumes:
      - mysql_data:/var/lib/mysql
      - ./app/.docker/mysql:/docker-entrypoint-initdb.d
    ports:
      - 8092:3306
    environment:
      - MYSQL_ROOT_PASSWORD=somepass
      - MYSQL_DATABASE=assignment
  app:
    build:
      dockerfile: Dockerfile
      target: dependencies
      context: ./app
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    volumes:
      - ./app/:/opt/application
    ports:
      - 8090:8080
  ui:
    build:
      dockerfile: Dockerfile
      target: dependencies
      context: ./ui
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    volumes:
      - ./ui/:/opt/application
      - /opt/application/node_modules
    environment:
      # Fixes file change detection: https://github.com/paulmillr/chokidar
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 8091:8080
